//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peri.BoxArrayBoardKerong.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1,0,0,10.10.10.210,5000</string>
  <string>2,1,0,10.10.10.210,5000</string>
  <string>3,2,0,10.10.10.210,5000</string>
  <string>4,3,0,10.10.10.210,5000</string>
  <string>5,4,0,10.10.10.210,5000</string>
  <string>6,5,0,10.10.10.210,5000</string>
  <string>7,6,0,10.10.10.210,5000</string>
  <string>8,7,0,10.10.10.210,5000</string>
  <string>9,8,0,10.10.10.210,5000</string>
  <string>10,9,0,10.10.10.210,5000</string>
  <string>11,10,0,10.10.10.210,5000</string>
  <string>12,11,0,10.10.10.210,5000</string>
  <string>13,12,0,10.10.10.210,5000</string>
  <string>14,13,0,10.10.10.210,5000</string>
  <string>15,14,0,10.10.10.210,5000</string>
  <string>16,15,0,10.10.10.210,5000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BoxList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BoxList"]));
            }
        }
    }
}
